### ISSUE TITLE
Got "SafeConfigParser instance has no attribute 'read_file'" when I tried to load a dataset

### ISSUE THREAD

**Issue by perryism** [datadotworld/data.world-py#53] opened 2017-07-05 17:50 UTC
I was in a conference and got this error and couldn't move forward. 

<pre>
dw.load_dataset('data-society/the-simpsons-by-the-data')

AttributeError                            Traceback (most recent call last)
<ipython-input-4-df0e98b7602b> in <module>()
----> 1 lds = dw.load_dataset('data-society/the-simpsons-by-the-data')  # , force_update=True)

/Users/plee/anaconda/lib/python2.7/site-packages/datadotworld/__init__.pyc in load_dataset(dataset_key, force_update, profile)
     87     ['changelog', 'datadotworldbballstats', 'datadotworldbballteam']
     88     """
---> 89     return _get_instance(profile).load_dataset(dataset_key,
     90                                                force_update=force_update)
     91 

/Users/plee/anaconda/lib/python2.7/site-packages/datadotworld/__init__.pyc in _get_instance(profile)
     42     if instance is None:
     43         config_param = (ChainedConfig()
---> 44                         if profile == 'default'
     45                         else FileConfig(profile=profile))
     46         instance = DataDotWorld(config=config_param)

/Users/plee/anaconda/lib/python2.7/site-packages/datadotworld/config.pyc in __init__(self, **kwargs)
    203         # Overrides (for testing)
    204         self._config_chain = kwargs.get('config_chain',
--> 205                                         [EnvConfig(), FileConfig()])
    206 
    207     def __getattribute__(self, item):

/Users/plee/anaconda/lib/python2.7/site-packages/datadotworld/config.pyc in __init__(self, profile, **kwargs)
    108 
    109         if path.isfile(self._config_file_path):
--> 110             self._config_parser.read_file(open(self._config_file_path))
    111             if self.__migrate_invalid_defaults(self._config_parser) > 0:
    112                 self.save()

AttributeError: SafeConfigParser instance has no attribute 'read_file'
</pre>

**Comment by rflprr** [comment] 2017-07-05 19:57
Hi, @perryism. Sorry for the trouble. To help us replicate the issue, would you mind sharing the output of `pip freeze`, so we can recreate an environment with all the same libraries and versions that you have? **After** running `pip freeze` you may want to upgrade `configparser` via `pip install --upgrade configparser` to see if that solves your issue.

**Comment by perryism** [comment] 2017-07-05 20:01
Sure.   Also, my `configparser` is up-to-date.

<pre>
airflow==1.7.1.3
alabaster==0.7.9
alembic==0.8.8
amqp==2.1.4
anaconda-client==1.6.0
anaconda-navigator==1.5
anaconda-project==0.4.1
ansible==2.2.0.0
appdirs==1.4.0
appnope==0.1.0
appscript==1.0.1
argcomplete==1.0.0
astroid==1.4.9
astropy==1.3
aws==0.2.5
awscli==1.11.56
Babel==2.3.4
backports-abc==0.5
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.4.0.2
beautifulsoup4==4.5.3
billiard==3.5.0.2
biplist==0.9
bitarray==0.8.1
blaze==0.10.1
bokeh==0.12.4
boto==2.45.0
boto3==1.4.0
botocore==1.5.19
Bottleneck==1.2.0
bz2file==0.98
cchardet==1.1.3
cdecimal==2.3
celery==4.0.2
certifi==2017.4.17
cffi==1.9.1
chardet==2.3.0
chartkick==0.4.2
chest==0.2.3
click==6.7
cloudpickle==0.2.2
clyent==1.2.2
colorama==0.3.7
conda==4.3.22
conda-build==2.1.15
conda-verify==2.0.0
configobj==5.0.6
configparser==3.5.0
construct==2.5.2
contextlib2==0.5.4
croniter==0.3.12
cryptography==1.7.1
cssselect==0.9.2
cycler==0.10.0
cymem==1.31.2
Cython==0.25.2
cytoolz==0.8.2
dask==0.13.0
datadotworld==1.2.5
datapackage==0.8.9
datashape==0.5.4
decorator==4.0.11
dill==0.2.5
docutils==0.13.1
dynd==0.7.3.dev1
ecdsa==0.13
en-core-web-sm==1.2.0
enum34==1.1.6
et-xmlfile==1.0.1
ezodf==0.3.2
Fabric==1.12.0
fastcache==1.0.2
filelock==2.0.7
Flask==0.12
Flask-Admin==1.4.0
Flask-Cache==0.13.1
Flask-Cors==3.0.2
Flask-Login==0.2.11
Flask-WTF==0.12
fn==0.4.3
funcsigs==1.0.2
functools32==3.2.3.post2
future==0.16.0
futures==3.0.5
gensim==1.0.1
geoip2==2.5.0
gevent==1.2.1
greenlet==0.4.11
grin==1.2.1
gunicorn==19.3.0
h5py==2.6.0
HeapDict==1.0.0
idna==2.2
ijson==2.3
imagesize==0.7.1
ipaddress==1.0.18
ipykernel==4.5.2
ipython==5.1.0
ipython-genutils==0.1.0
ipywidgets==5.2.2
isign==1.6.10
isodate==0.5.4
isort==4.2.5
itsdangerous==0.24
jdcal==1.3
jedi==0.9.0
Jinja2==2.9.5
jmespath==0.9.1
jsonlines==1.1.2
jsonschema==2.5.1
jsontableschema==0.10.1
jupyter==1.0.0
jupyter-client==4.4.0
jupyter-console==5.0.0
jupyter-core==4.2.1
Keras==2.0.4
kombu==4.0.2
lazy-object-proxy==1.2.2
linear-tsv==1.0.0
llvmlite==0.15.0
locket==0.2.0
lockfile==0.12.2
lxml==3.7.2
Mako==1.0.4
Markdown==2.6.7
MarkupSafe==0.23
matplotlib==2.0.0
maxminddb==1.3.0
memoizer==0.0.1
mistune==0.7.3
mock==2.0.0
mpmath==0.19
multipledispatch==0.4.9
murmurhash==0.26.4
mxnet==0.7.0
MySQL-python==1.2.5
nb-anacondacloud==1.2.0
nb-conda==2.2.0
nb-conda-kernels==2.0.0
nbconvert==4.2.0
nbformat==4.2.0
nbpresent==3.0.2
networkx==1.11
nltk==3.2.2
nose==1.3.7
notebook==4.3.1
numba==0.30.1+0.g8c1033f.dirty
numexpr==2.6.1
numpy==1.13.0
numpydoc==0.6.0
odo==0.5.0
openpyxl==2.4.1
packaging==16.8
pandas==0.20.2
paramiko==1.17.2
partd==0.3.7
pathlib==1.0.1
pathlib2==2.2.0
patsy==0.4.1
pbr==1.10.0
pep8==1.7.0
pexpect==4.2.1
pickleshare==0.7.4
Pillow==4.0.0
pkginfo==1.4.1
plac==0.9.6
ply==3.9
preshed==1.0.0
prettytable==0.7.2
prompt-toolkit==1.0.9
protobuf==3.0.0b2
psutil==5.0.1
psycopg2==2.7.1
ptyprocess==0.5.1
py==1.4.32
pyasn1==0.2.3
PyAudio==0.2.7
PyContracts==1.7.15
pycosat==0.6.1
pycparser==2.17
pycrypto==2.6.1
pycurl==7.43.0
pyflakes==1.5.0
Pygments==2.1.3
pylint==1.6.4
PyMySQL==0.7.6
pyOpenSSL==16.2.0
pyparsing==2.1.10
pyquery==1.2.13
PySocks==1.6.7
pysqlcipher==2.6.5
pytest==3.0.5
python-daemon==2.1.2
python-dateutil==2.6.0
python-editor==1.0.1
pytz==2017.2
PyYAML==3.12
pyzmq==16.0.2
QtAwesome==0.4.3
qtconsole==4.2.1
QtPy==1.2.1
redis==2.10.5
requests==2.13.0
rfc3986==0.4.1
rope==0.9.4
rq==0.8.0
rq-scheduler==0.7.0
rsa==3.4.2
s3transfer==0.1.10
scandir==1.4
scikit-image==0.12.3
scikit-learn==0.18.1
scipy==0.19.0
seaborn==0.7.1
setproctitle==1.1.10
simplegeneric==0.8.1
simplejson==3.9.0
singledispatch==3.4.0.3
six==1.10.0
smart-open==1.5.1
snowballstemmer==1.2.1
sockjs-tornado==1.0.3
spacy==1.7.3
Sphinx==1.5.1
sphinx-rtd-theme==0.2.4
spyder==3.1.2
SQLAlchemy==1.1.5
sqlalchemy-redshift==0.6.0
sshtunnel==0.1.2
statsmodels==0.6.1
stop-words==2015.2.23.1
subprocess32==3.2.7
sympy==1.0
tables==3.3.0
tabulator==1.1.0
tensorflow==0.10.0
termcolor==1.1.0
terminado==0.6
Theano==0.9.0
thinc==6.5.2
thrift==0.9.3
toolz==0.8.2
tornado==4.4.2
tqdm==4.11.2
traitlets==4.3.1
ujson==1.35
unicodecsv==0.14.1
urllib3==1.21.1
vine==1.1.3
virtualenv==15.0.2
wcwidth==0.1.7
Werkzeug==0.11.15
widgetsnbextension==1.2.6
wrapt==1.10.10
WTForms==2.1
xlrd==1.0.0
XlsxWriter==0.9.6
xlwings==0.10.2
xlwt==1.2.0
</pre>

**Comment by rflprr** [comment] 2018-02-15 19:01
@perryism, we have been unable to reproduce this issue. Closing now, but feel free to comment if it is still a problem for you.

**Closed by rflprr** 2018-02-15 19:01 UTC
Labels: bug
